name: Deploy Notifications

on:
  push:
    branches:
      - '**'

  pull_request_target:
    branches:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"

          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "Webhook missing"
            exit 1
          else
            echo "Webhook exists"
          fi

      - uses: actions/checkout@v4

      - name: Fake deploy
        run: echo "Deploying..."

      - name: Send Discord notification
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "Repository updated"
          title: "deploy"
          description: |
            Event: ${{ github.event_name }}
            Ref: ${{ github.ref_name }}
            Actor: ${{ github.actor }}
          color: 0x0000ff
          username: GitHub Actions
